version: '3.8'

services:
  # Laravel PHP-FPM Service
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: app-1
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8090:8090"
    networks:
      - public
      - internal
    env_file:
      - .env
    environment:
      - APP_URL=${APP_URL}
      - APP_ENV=${APP_ENV}
      - DB_HOST=${MYSQL_HOST}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_PORT=${MYSQL_PORT}
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=rabbitmq
      - TASK_EXPIRATION_TIME=${TASK_EXPIRATION_TIME}
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}

  nginx:
    image: nginx:latest
    container_name: app-backend-1
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./app:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - public
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: ${MYSQL_HOST}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - internal

  adminer:
    image: adminer
    container_name: adminer-1
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - internal

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis-1
    restart: unless-stopped
    networks:
      - internal

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    networks:
      - internal

  conversion_service:
    build:
      context: ./services/conversion
    container_name: conversion_service
    restart: unless-stopped
    volumes:
      - ./services/conversion:/app
      - ./app/storage/app/private/uploads:/app/storage
    depends_on:
      - rabbitmq
      - app
    environment:
      - QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox"
      - RABBITMQ_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
    networks:
      - internal
  uniconvertor:
    build:
      context: ./services/uniconvertor
    container_name: uniconvertor
    restart: unless-stopped
    volumes:
      - ./services/uniconvertor:/app
      - ./app/storage/app/private/uploads:/app/storage
    depends_on:
      - rabbitmq
      - app
    networks:
      - internal

  pdf2htmlex:
    build:
      context: ./services/pdf2htmlex
    container_name: pdf2htmlex
    restart: unless-stopped
    volumes:
      - ./services/pdf2htmlex:/app
      - ./app/storage/app/private/uploads:/app/storage
    networks:
      - internal
networks:
  public:
    driver: bridge
  internal:
    driver: bridge

